---
ID: "3b50ebd6-0a8e-4b2d-b53a-64370fff4269"
Parent: "552d08f6-a47d-4a2c-bf46-326589a65f27"
Template: "552d08f6-a47d-4a2c-bf46-326589a65f27"
Path: /sitecore/templates/TAC/Events/Base/_Base Content/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "01b9114b-4229-4ba3-976c-7b4478b20228"
      Hint: ContentHeading
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220817T021438Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4ab82c0e-30cd-4c12-aa1a-dca3e21c06e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220817T021454Z
